### ISSUE TITLE
Overlay media cannot be removed

### ISSUE THREAD

**Issue by lslavkov** [abdelaz3r/forbidden_lands#40]
**Describe the bug**
Added media does not being removed

**To Reproduce**
1. Add media overlay
2. Click on button to remove it

**Expected behavior**
Media overlay should be removed

**Screenshots**

**Desktop:**
 - Elixir 1.12.2

**Comment by abdelaz3r** [comment]
You're right! I'll fix that, thanks.

**Comment by abdelaz3r** [comment]
Fixed!
